export const FONT_CATALOG: Record<string, string[]> = {
  Serif: [
    "Abril Fatface",
    "Alegreya",
    "Arvo",
    "Instrument Serif",
    "BioRhyme",
    "Corben",
    "Cormorant",
    "Courier Prime",
    "Coustard",
    "DM Serif Display",
    "Eczar",
    "Frank Ruhl Libre",
    "Gravitas One",
    "IBM Plex Serif",
    "Jomolhari",
    "Libre Baskerville",
    "Lora",
    "Merriweather",
    "Neuton",
    "Noto Serif",
    "Old Standard TT",
    "PT Serif",
    "Playfair Display",
    "Prata",
    "Source Serif Pro",
    "Spectral",
    "Vollkorn",
  ],
  "Sans Serif": [
    "Alegreya Sans",
    "Anton",
    "Archivo",
    "Barlow",
    "Archivo Narrow",
    "Cabin",
    "Catamaran",
    "Chivo",
    "Fira Sans",
    "IBM Plex Sans",
    "Karla",
    "Lato",
    "Libre Franklin",
    "Montserrat",
    "Muli",
    "Noto Sans",
    "Nunito",
    "Open Sans",
    "Oswald",
    "Oxygen",
    "PT Sans",
    "Pontano Sans",
    "Poppins",
    "Puritan",
    "Raleway",
    "Roboto",
    "Source Sans Pro",
    "Space Mono",
    "Titillium Web",
    "Ubuntu",
    "Varela",
    "Work Sans",
  ],
  Display: [
    "Caveat",
    "Courgette",
    "Delius",
    "Kalam",
    "Merienda",
    "Patrick Hand",
    "Permanent Marker",
    "Press Start 2P",
    "Satisfy",
    "VT323",
  ],
  International: [
    "Noto Sans SC",
    "Noto Sans TC",
    "Noto Sans JP",
    "Noto Sans KR",
  ],
};

/** Flat set of all valid font names for validation */
export const VALID_FONTS = new Set(Object.values(FONT_CATALOG).flat());
