"use client";

import Image from "next/image";
import "./hero-animation.css";

const LOOP = "8.6s infinite both";

export function HeroAnimation() {
  return (
    <div aria-hidden="true" className="hero-animation">
      {/* Terminal chrome */}
      <div className="border-2 border-brand bg-brand shadow-[6px_6px_0_var(--color-brand)]">
        {/* Title bar */}
        <div className="border-b-2 border-surface/20 px-3 py-1.5 flex items-center gap-1.5">
          <span className="block h-2 w-2 border border-surface/30 bg-gold" />
          <span className="block h-2 w-2 border border-surface/30 bg-surface/20" />
          <span className="block h-2 w-2 border border-surface/30 bg-surface/20" />
          <span className="font-[family-name:var(--font-geist-mono)] text-[10px] text-surface/40 ml-2">
            terminal
          </span>
        </div>

        {/* Code content */}
        <div className="relative p-3 md:p-4 font-[family-name:var(--font-geist-mono)] text-[10px] md:text-xs leading-relaxed min-h-[140px]">
          {/* Line 1: curl command */}
          <div
            className="hero-typing overflow-hidden whitespace-nowrap"
            style={{ animation: `type-line1 ${LOOP}`, width: 0, opacity: 0, animationTimingFunction: "steps(42, end)" }}
          >
            <span className="text-[#ff9f6b]">curl</span>
            <span className="text-surface/90"> -X POST bragfast.com/api/v1/release \</span>
          </div>

          {/* Line 2: payload */}
          <div
            className="hero-typing overflow-hidden whitespace-nowrap"
            style={{ animation: `type-line2 ${LOOP}`, width: 0, opacity: 0, animationTimingFunction: "steps(37, end)" }}
          >
            <span className="text-surface/90">{"  -d '"}</span>
            <span className="text-[#6bff6b]">{`{ "title": "Fresh new look" }`}</span>
            <span className="text-surface/90">{"'"}</span>
          </div>

          {/* Blinking cursor — visible only during typing phases */}
          <span
            className="inline-block text-surface/80"
            style={{
              animation: `cursor-blink 0.8s steps(1) infinite, cursor-visible ${LOOP}`,
              opacity: 0,
            }}
          >
            ▌
          </span>

          {/* Blank line */}
          <div className="h-4" />

          {/* 202 response */}
          <div style={{ animation: `fade-202 ${LOOP}`, opacity: 0 }}>
            <span className="text-gold">← 202 Accepted</span>
            <span className="text-surface/60">{`  { release_id: "rel_a1b2c3" }`}</span>
          </div>

          {/* Blank line */}
          <div className="h-4" />

          {/* Processing */}
          <div style={{ animation: `fade-processing ${LOOP}`, opacity: 0 }}>
            <span className="text-surface/50">Generating images...</span>
          </div>

          {/* Blank line */}
          <div className="h-4" />

          {/* 200 webhook */}
          <div style={{ animation: `fade-200 ${LOOP}`, opacity: 0 }}>
            <span className="text-[#6bff6b]">← 200 OK</span>
            <span className="text-surface/60"> (webhook)  3 images ready</span>
          </div>
        </div>
      </div>

      {/* Image fan — overlaps terminal, hidden below sm */}
      <div className="flex items-end justify-center gap-2 -mt-8 hidden sm:flex" style={{ zIndex: 10 }}>
        {/* Landscape */}
        <div
          className="hero-fan-img border-2 border-brand shadow-[3px_3px_0_var(--color-brand)]"
          style={{ animation: `fan-landscape ${LOOP}`, opacity: 0 }}
        >
          <Image
            src="/demo/standard-browser-inter-landscape.jpg"
            alt="Example landscape social image generated by bragfast"
            width={160}
            height={90}
            className="block"
          />
        </div>

        {/* Square */}
        <div
          className="hero-fan-img border-2 border-brand shadow-[3px_3px_0_var(--color-brand)]"
          style={{ animation: `fan-square ${LOOP}`, opacity: 0 }}
        >
          <Image
            src="/demo/standard-browser-inter-square.jpg"
            alt="Example square social image generated by bragfast"
            width={90}
            height={90}
            className="block"
          />
        </div>

        {/* Portrait */}
        <div
          className="hero-fan-img border-2 border-brand shadow-[3px_3px_0_var(--color-brand)]"
          style={{ animation: `fan-portrait ${LOOP}`, opacity: 0 }}
        >
          <Image
            src="/demo/standard-browser-inter-portrait.jpg"
            alt="Example portrait social image generated by bragfast"
            width={65}
            height={86}
            className="block"
          />
        </div>
      </div>
    </div>
  );
}
