import { describe, it, expect } from "vitest";
import { validateDraftPayload } from "../validate";

describe("validateDraftPayload", () => {
  it("accepts minimal image payload", () => {
    const r = validateDraftPayload({ output: "image" });
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.config.output).toBe("image");
  });

  it("accepts full payload", () => {
    const r = validateDraftPayload({
      name: "Release v2",
      output: "video",
      templateId: "standard-browser",
      brandId: "brand_abc",
      colors: { background: "#fff", text: "#000", primary: "#f00" },
      formats: ["landscape", "square"],
      objectContent: {
        "headline-0": { text: "Hi" },
        "image-0": { image_url: "https://x/y.png", video_url: "https://x/y.mp4" },
      },
      video: { duration: 12, preset: "showcase" },
      notes: "generated by agent",
    });
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.name).toBe("Release v2");
      expect(r.config.formats).toEqual(["landscape", "square"]);
      expect(r.config.objectContent?.["image-0"].image_url).toBe("https://x/y.png");
    }
  });

  it("rejects missing output", () => {
    const r = validateDraftPayload({});
    expect(r.ok).toBe(false);
  });

  it("rejects unknown top-level keys", () => {
    const r = validateDraftPayload({ output: "image", bogus: 1 });
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error).toMatch(/bogus/);
  });

  it("rejects bad output enum", () => {
    const r = validateDraftPayload({ output: "gif" });
    expect(r.ok).toBe(false);
  });

  it("rejects bad format enum", () => {
    const r = validateDraftPayload({ output: "image", formats: ["huge"] });
    expect(r.ok).toBe(false);
  });

  it("rejects non-string templateId", () => {
    const r = validateDraftPayload({ output: "image", templateId: 123 });
    expect(r.ok).toBe(false);
  });

  it("rejects unknown keys in objectContent entries", () => {
    const r = validateDraftPayload({
      output: "image",
      objectContent: { title: { bogus: "wrong field" } },
    });
    expect(r.ok).toBe(false);
  });

  it("rejects bad video preset", () => {
    const r = validateDraftPayload({
      output: "video",
      video: { preset: "not-a-preset" },
    });
    expect(r.ok).toBe(false);
  });

  it("rejects non-positive duration", () => {
    const r = validateDraftPayload({ output: "video", video: { duration: 0 } });
    expect(r.ok).toBe(false);
  });

  it("rejects bad colors shape", () => {
    const r = validateDraftPayload({
      output: "image",
      colors: { background: "#fff" },
    });
    expect(r.ok).toBe(false);
  });
});
